# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Fuckologyunofficial
description: >- # this means to ignore newlines until "baseurl:"
  Thoutfully unstable.
baseurl: "/bay" # the subpath of the site
url: "https://fuckologyunofficial.club" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: ""

header:
  pages:
    - name: Home
      slug: /
    - name: Work

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: hello@fuckologyunofficial.club
      link: mailto:bhaskar@internet.ru
  follow:
    - name: Twitter
      link: http://twitter.com/fuckologyuboff
      username: "@fuckologyunoff"
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
